### ISSUE TITLE
[🙏] Add ability to target specific namespaces

### ISSUE THREAD

**Issue by bert-huang** [snyk/kubernetes-monitor#1172]
**Describe the user need**
Currently, the `kubernetes-monitor` by default scans for pods in all namespaces (with some default exclusions), and have the capability to exclude namespaces via the `excludedNamespaces` option.

It will be useful if there is the ability to target specific namespaces instead of having to find all other namespaces to exclude.

**Describe expected behaviour**
Have the ability to specify `includedNamespaces` option during the helm upgrade to tell the `snyk-monitor` to only scan the specified namespaces. Similar to `excludedNamespaces`, this can be a list.

```
helm upgrade --install snyk-monitor snyk-charts/snyk-monitor \ 
             --namespace snyk-monitor \
             --set includedNamespace="{some_namespace}"
```

This will take precedence over the `excludedNamespaces`, so if a namespace is specified on both the `includeNamespaces` and the `excludedNamepsaces` then the `includedNamespaces` will take effect.

**Additional context**
Our organisation is grouping kubernetes scan results into separate Snyk orgs. To achieve this, a `snyk-monitor` is deployed into each namespace. However, each `snyk-monitor` should only scan its own namespace. The existing exclusion approach works but not ideal since if a new namespace is added, all `snyk-monitor` deployments will need to be re-deployed to have that new namespace excluded.

**Comment by kat1906** [comment]
hi @bert-huang, we already provide this functionality - please see here: https://github.com/snyk/kubernetes-monitor/issues/1172

Let me know if this is suitable for your use case :)

**Comment by bert-huang** [comment]
Hi @kat1906, sorry but the issue link you've provided links to this issue. I've checked the source and seems the only way to target a specific namespace at the moment is by excluding all others using `excludedNamespaces`.

**Comment by kat1906** [comment]
sorry, not sure why that happened - I meant this link: https://github.com/snyk/kubernetes-monitor#installation-from-yaml-files
