### ISSUE TITLE
Snyk K8S Integration | Allow anonymous user to push results to any Org  🐛

### ISSUE THREAD

**Issue by bugwrangler** [snyk/kubernetes-monitor#1205]
### Expected behaviour
Snyk should only allow authenticated users to push results,  This should be based on authorization to service or user API token. 

### Actual behaviour
Allow anonymous users to push results to any Org (NO  Snyk API key needed) 

### Steps to reproduce
helm repo add snyk-charts https://snyk.github.io/kubernetes-monitor --force-update
kubectl create namespace snyk-monitor
kubectl create secret generic snyk-monitor -n snyk-monitor \
--from-literal=integrationId=abcd1234-abcd-1234-abcd-1234abcd1234
helm upgrade --install snyk-monitor snyk-charts/snyk-monitor \
             --namespace snyk-monitor \
             --set clusterName="Production cluster"
 
 
https://github.com/snyk/kubernetes-monitor/blob/staging/src/transmitter/index.ts#L379
 
url: `${upstreamUrl}/api/v1/runtime-results`
 
https://github.com/snyk/kubernetes-monitor/blob/staging/src/transmitter/index.ts#L98
url: `${upstreamUrl}/api/v1/scan-results`,

**Comment by ivanstanev** [comment]
Hey @bugwrangler ,

Thank you for raising this issue. We are aware of the behaviour which you describe and after a thorough investigation and analysis from our applications security team, we consider it unlikely that it would have any significant impact on us or any customer.

We do plan to improve on this behaviour in the near future in line with a larger engineering effort that is currently being planned.

**Comment by bugwrangler** [comment]
@ivanstanev  How would you say this would not be a significant impact on your customers? I am one of your enterprise customers. An Enterprise group member can fetch all Organisation IDs using the API, 
using the Org ID all of our engineers (approx 1k+) are allowed to push results to the Snyk Platform on any random ORg. 

Are you suggesting Snyk engineering team is promoting API which doesn't have Authentication & Authorization?

**Comment by bugwrangler** [comment]
API doesn't have API authentication is a vulnerability, This API endpoint should be fixed or deprecated - https://github.com/OWASP/API-Security/blob/master/2019/en/src/0xa2-broken-user-authentication.md
