### ISSUE TITLE
Ability to specify nodeSelector in the Helm chart

### ISSUE THREAD

**Issue by adhodgson1** [snyk/kubernetes-monitor#531]
Can we get the ability to specify the nodeSelector in the Helm chart? This would be handy where we want the monitor to run on a specific set of machines. At present this facility is not available.

**Comment by ivanstanev** [comment]
Hey 👋 Sure thing, we will add it to our backlog! Can't give an exact estimate when we will pick it up but perhaps in the next few weeks! Alternatively if this is something you would like done sooner we are also happy to accept a PR

**Comment by shaimendel** [comment]
This issue is solved in https://github.com/snyk/kubernetes-monitor/releases/tag/v1.31.0 - thank you for the contribution @adhodgson1!
