### ISSUE TITLE
Add support for and/or document credHelper dockerconfig option

### ISSUE THREAD

**Issue by redbaron** [snyk/kubernetes-monitor#568]
When running inside GKE cluster with Workload Identity enabled following docker config enabled access to the registry without managing static credentials:

```
{
  "credHelpers": {
    "gcr.io": "gcloud",
    "marketplace.gcr.io": "gcloud",
    "eu.gcr.io": "gcloud",
    "us.gcr.io": "gcloud",
    "staging-k8s.gcr.io": "gcloud",
    "asia.gcr.io": "gcloud"
  }
}
```

It would be great if snyk-monitor image and helm chart contained gcloud CLI tool and supported this mode of operation

**Comment by shaimendel** [comment]
Hi @redbaron, thank you for raising this!
As far as you know - doing the two steps you mentioned (specifying the above docker config + having the gcloud CLI locally) is enough? no gcloud commands needs to be run in the container? (like `gcloud auth` etc)

**Comment by redbaron** [comment]
@shaimendel , no  need to run any commands, as long as `gcloud` CLI is present it works out of the box

**Comment by 0x91** [comment]
we'd also like this for AWS which uses https://github.com/awslabs/amazon-ecr-credential-helper

**Comment by dkontorovskyy** [comment]
@0x91 thanks for raising this!

I added your comment to our backlog ticket. We will try to schedule this work as soon as possible 🤗

**Comment by 0x91** [comment]
@dkontorovskyy I'm happy to have a go, I believe there is enough functionality present with skopeo and passing in the dockerConfig we just need the credential-helper built into the Docker container.

Understandably this does introduce some bloat. I see a PR open to add gcloud in https://github.com/snyk/kubernetes-monitor/pull/749

Would a PR to add the credential helper be acceptable? AFAIK the versions are all backwards compatible with eachother

**Comment by dkontorovskyy** [comment]
@0x91 It's going to be next in work :) `gcould` goes in and `ecr` will be next

**Comment by kat1906** [comment]
@redbaron gcloud is in and ready to go if you want to try it out with the latest release 🎉

**Comment by richerve** [comment]
@dkontorovskyy any estimate on when the ecr-credential-helper can be included in the docker image? Maintaining a custom image just to include that it's difficult as there's no artifact published here so it basically requires copying the whole Dockerfile and building from scratch, just to add an extra `go get` for the ecr credentials, that is a method described in https://github.com/awslabs/amazon-ecr-credential-helper#from-source. Thanks

**Comment by chen-keinan** [comment]
@richerve a release with support of `ecr-credential-helper` has been published, if you want you can try it with our latest release

**Comment by richerve** [comment]
> @richerve a release with support of `ecr-credential-helper` has been published, if you want you can try it with our latest release

Thank you, at the end I didn't use it as our k8s nodes already have a role to communicate with ecr, but I see a lot of value on adding this helper anyway for people not running in AWS or with a different credentials scheme
