### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by Joeskyyy** [snyk/kubernetes-monitor#571]
Hey folks, just curious if there are any changelogs published for the helm charts somewhere? Looking to do some upgrades and couldn't find any for the version changes.

**Comment by agatakrajewska** [comment]
Hi @Joeskyyy!

We don't have a changelog file at the moment, although it's not out of the question we will in the future. 
Currently you can see version changes browsing the commits thought the github releases only. 

Hope that helps,
Agata
