### ISSUE TITLE
helm upgrade failed with pvc.enabled but without pvc.storageClassName

### ISSUE THREAD

**Issue by DmitriyStoyanov** [snyk/kubernetes-monitor#667]
We faced with error:
`Error: UPGRADE FAILED: cannot patch "snyk-monitor-pvc" with kind PersistentVolumeClaim: PersistentVolumeClaim "snyk-monitor-pvc" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims`

with adding pvc.enabled but without setting pvc.storageClassName.

On first execution it takes default class, but on second upgrade it cannot change, because of null in storage class variable.

It can be fixed as described here: https://github.com/helm/charts/issues/20389#issuecomment-583854511

I'll submit MR in near future

**Comment by ivanstanev** [comment]
Hey @DmitriyStoyanov, thanks for raising this. A PR would be much appreciated but even if you can't create one we will try to handle it from our side in the next couple of weeks!

**Comment by DmitriyStoyanov** [comment]
@ivanstanev could you review raised PR #668 ?
