### ISSUE TITLE
Snyk complains about this image because of vulnerabilities in Skopeo

### ISSUE THREAD

**Issue by Niksko** [snyk/kubernetes-monitor#684]
Snyk currently flags this image because it includes Skopeo. Skopeo's `go.sum` has a vulnerable version of `ulikunitz/xz`, the project but doesn't actually use this version (as verified by looking at the `vendor/modules.txt`).

The next release of Skopeo should not have this in the `go.sum`, which will fix Synk's issue with it. When possible, this project should update Skopeo.

**Comment by jmickey** [comment]
Hi @Niksko! Thanks so much for raising this. We're aware of this issue and we're in the process of updating our dependencies to get this fixed up. 

I'll leave this issue open for the moment and we'll let you know once we've sorted this out.

**Comment by ivanstanev** [comment]
Hey @Niksko with PR https://github.com/snyk/kubernetes-monitor/pull/686 this should now be resolved :)
