### ISSUE TITLE
Pod restart every hour

### ISSUE THREAD

**Issue by rumi-spock** [snyk/kubernetes-monitor#741]
This is not really a bug but seems like what is now deployment should be actually a job. Right now pod restarts every hour and on each run it scans the containers, syncs with Snyk and then does nothing until it gets killed after an hour. 
Firstly it should run as a job which once done will be marked as completed so you won't get a running idle container which eventually gets killed. Right now I have this pod running for 2 days and it already shows 40 restarts. We have alerts based on frequent restarts because this many restarts means something is wrong. 
Secondly if it is configured as job/cronjob then we can set the frequency ourselves. E.g. we would like to sync it every 15 mins instead of 1 hour.
Let me know if this makes sense.

**Comment by dkontorovskyy** [comment]
@rumi-spock 👋 
We have a scheduled brainstorming in this area for the next week.

Currently what you see is actually 3rd library issues that led to this amount of restarts for the pod. We want to make sure this won't happen but want to do it properly. Bare with us 🤗

**Comment by CamillaBLarsen** [comment]
We have the same issue - but also that it pressures the disk quite much, due to the frequent restarts.

**Comment by dkontorovskyy** [comment]
@rumi-spock @CamillaBLarsen could you try new `kubernetes-monitor` version and see if it helps, please? 
Newly released version is `1.55.0`

**Comment by CamillaBLarsen** [comment]
It's much more stable now, compared to the previous version.
Have a look, marked with red (orange) was version 1.54, marked with red (blue) is the current 1.55.
![image](https://user-images.githubusercontent.com/52245320/118797766-31cfa480-b89d-11eb-83bd-3000790eb4cd.png)

**Comment by rumi-spock** [comment]
Thanks for fixing it. I have tested it with version 1.55.0 today and it looks good.
