### ISSUE TITLE
[🐛] snyk-monitor Chart: Specify custom Configmap with rego policy for import/export

### ISSUE THREAD

**Issue by richerve** [snyk/kubernetes-monitor#809]
- `kubernetes-monitor version: v1.64.1` 
- `Cloud runtime: custom kops based`

### Expected behaviour

The helm chart `workloadPoliciesMap` value will allow to specify a configmap including custom rego policies under the `workload-events.rego` key. Changing that value in `values.yaml` must not have any effect in the included default policy.

### Actual behaviour

Here's a couple of options I have in mind:

1. (preferred) Use `workloadPoliciesMap` in values.yaml to point to a pre-created custom ConfigMap and mount that in the deployment. The ConfigMap in the Chart containing the default policy, should have a fixed name, not configurable (but documented, of course).
2. Add a new option in values.yaml to point to the external ConfigMap and adjust the Deployment accordingly.

### Steps to reproduce

Set `workloadPoliciesMap` to a name of an existing ConfigMap having the custom policies. The helm release will fail as a ConfigMap with the same name is already part of the helm release.

**Comment by kat1906** [comment]
Hi @richerve thanks for raising this issue.

I'll take it to the team and we'll get back to you 🙂

**Comment by richerve** [comment]
I'm working in a PR already that I'm planning to submit, if that's ok

**Comment by kat1906** [comment]
Even better! Thanks

**Comment by richerve** [comment]
@kat1906 https://github.com/snyk/kubernetes-monitor/pull/812

**Comment by dkontorovskyy** [comment]
@richerve it's merged :) Can you go and check `v1.64.4`? :)

**Comment by dkontorovskyy** [comment]
@richerve have you had any chance to check? 🤗

**Comment by richerve** [comment]
> @richerve have you had any chance to check? hugs

yes, all looks good, thanks

**Comment by dkontorovskyy** [comment]
Closing it as fixed :) 

Reached you out via email to send you swag for the amazing PR you've opened!
