### ISSUE TITLE
[🙏] Revisit readiness and liveness probes for k8s deployment

### ISSUE THREAD

**Issue by vmaillot** [snyk/kubernetes-monitor#849]
**Describe the user need**
Would it be possible to set effective liveness and readiness probe on the kubernetes-monitor [deployment](https://github.com/snyk/kubernetes-monitor/blob/staging/snyk-monitor/templates/deployment.yaml#L132-L139)?

**Describe expected behaviour**

At the moment, the kubernetes-monitor pod is always starting and working well. But in case of issues from the application itself, Kubernetes will not detect that the pod is having issues if we do not set propre and effective liveness/readiness probe.

Would it be possible to get some accurate ones?

Thanks in advance!

**Comment by minsiyang** [comment]
Hi @vmaillot, thank you very much for raising this issue. I have brought it to the team's attention. I will get back to you as soon as we reach a decision 😄

**Comment by vmaillot** [comment]
Hey @minsiyang,

Alright got it! The thing is we need a way to be sure that the applicatin is behaving like expected. This can be done with such `liveness` and `readiness` probes.

Now the question is, is the `snyk-monitor` already able to expose and endpoint that can be poked? Therefore we could use that endpoint as a probe.

Thanks for letting me know what do you guys think!

Have a nice day!

**Comment by ivanstanev** [comment]
Hey @vmaillot closing this because we don't have a good candidate for setting liveness and readiness probes, as @minsiyang mentioned!
