### ISSUE TITLE
[🙏] Make NetworkPolicy an optional resource

### ISSUE THREAD

**Issue by stephencoe** [snyk/kubernetes-monitor#984]
**Describe the user need**
The network policy that comes with the monitor opens egress to the world. 

We are currently using Cilium for all network policies within the cluster but it appears with both existing the cilium policy is respecting the network policy so this component has unrestricted egress. 

**Describe expected behaviour**

Being able to disable the NetworkPolicy would allow us to control the egress to known destinations

**Comment by kat1906** [comment]
Hi @stephencoe, thank you very much for raising this issue. I will get back to you as soon as I have discussed it with the team. 😃

We are more than willing to accept PRs if this is something you might be interested in assisting with!

**Comment by stephencoe** [comment]
@kat1906 Thanks, I will submit a PR for this

**Comment by minsiyang** [comment]
Hi @stephencoe , we just merged the PR today. If you use the latest snyk-monitor v1.79.0, you should be able to disable the networkPolicy now. Thank you for your contribution!  😄
